WOA.WebMVC/Models/ErrorViewModel.cs
namespace WOA.WebMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WOA.WebMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WOA.WebMVC.Models;

namespace WOA.WebMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WOA.WebMVC/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
//using Microsoft.AspNetCore.Mvc;
//using WOA.Contracts;
//using WOA.Models;
//using WOA.Services;

//namespace WOA.WebMVC.Controllers
//{
//    public class ItemController : Controller
//    {

//        private readonly IItemService _itemService;

//        public ItemController(IItemService itemService)
//        {
//            _itemService = itemService;
//        }

//        public IActionResult Index()
//        {
//            var item = new ItemListItem[0];
//            return View(item);
//        }

//        public IActionResult Create()
//        {
//            return View();

//        }

//    }
//}

WOA.WebMVC/Controllers/ListingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WOA.Contracts;
using WOA.Data;
using WOA.Models;
using WOA.Services;

namespace WOA.WebMVC.Controllers
{
    
    public class ListingController : Controller
    {

        private readonly IListingService _listingService;

        public ListingController(IListingService listingService)
        {
            _listingService = listingService;
        }

        public IActionResult Index()
        {
            if (!SetUserId()) return Unauthorized();
            //var userId = Guid.Parse(User.Identity.GetUserId());
            var listing = new ListingListItem[0];
            return View(listing);
        }

        public IActionResult IndexGetId(int id)
        {
            var model = _listingService.GetListingsByUserId(id);
            return View(model);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ListingCreate model)
        {
            if (ModelState.IsValid)
            {

            }
            return View(model);
        }

        private string GetUserId()
        {
            string userIdClaim = User.Claims.First(i => i.Type == ClaimTypes.NameIdentifier).Value;
            if (userIdClaim is null) return null;
            return userIdClaim;
        }

        private bool SetUserId()
        {
            string userId = GetUserId();
            if (userId == null) return false;

            _listingService.SetUserId(Guid.Parse(userId));
            return true;
        }
    }
}

WOA.WebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WOA.WebMVC/Views/Item/Create.cshtml
@*@model WOA.Models.ItemCreate

@{ ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Length" class="control-label"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimePeriod" class="control-label"></label>
                <input asp-for="TimePeriod" class="form-control" />
                <span asp-validation-for="TimePeriod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Item</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

WOA.WebMVC/Views/Item/Index.cshtml
@*@model IEnumerable<WOA.Models.ItemListItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Condition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimePeriod)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Length)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Width)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Condition)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimePeriod)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ItemId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ItemId }) |
                </td>
            </tr>
        }
    </tbody>
</table>*@

WOA.WebMVC/Views/Listing/Create.cshtml
@model WOA.Models.ListingCreate

@{ ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Listing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="condition" class="control-label">Condition</label>
                <input asp-for="condition" class="form-control" />
                <span asp-validation-for="condition" class="text-danger"></span>
            </div>*@
            <div>
                <select class="form-select" aria-label="condition">
                    <option selected>Condition</option>
                    <option value="Fair">Fair</option>
                    <option value="Good">Good</option>
                    <option value="Mint">Mint</option>
                </select>
   
            </div>


            <div>
                <select class="form-select" aria-label="timePeriod">
                    <option selected>Time Period</option>

                    <option value="WilliamandMary">William and Mary - 1685-1720</option>

                    <option value="QueenAnneLouisXV">Queen Anne/Louis XV - 1720-1760</option>

                    <option value="Chippendale">Chippendale - 1755-1790</option>

                    <option value="FederalHepplewhite">Federal/ Hepplewhite - 1790-1815</option>

                    <option value="Sheraton">Sheraton - 1790-1810</option>

                    <option value="Empire">Empire - 1805-1830</option>

                    <option value="Victorian">Victorian - 1830-1901</option>

                    <option value="RococoRevival">Rococo Revival - 1845-1870</option>

                    <option value="NaturalisticAesthetic">Naturalistic/Aesthetic - 1850-1914</option>

                    <option value="NeoGreekEastlake">Neo-Greek/Eastlake - 1855-1890</option>

                    <option value="ArtsandCrafts">Arts and Crafts - 1895-1915</option>

                    <option value="ArtNouveau">Art Nouveau - 1896-1914</option>

                    <option value="ArtDeco">Art Deco - 1920-1945</option>

                    <option value="MidCenturyModernism">Mid-Century Modernism - 1945-1970</option>
                </select>

            </div>


            @*<div class="form-group">
                <label asp-for="timePeriod" class="control-label">Time Period</label>
                <input asp-for="timePeriod" class="form-control" />
                <span asp-validation-for="timePeriod" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listings</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WOA.WebMVC/Views/Listing/Index.cshtml
@model IEnumerable<WOA.Models.ListingListItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ListingId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Availability)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.condition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.timePeriod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePosted)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ListingId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Availability)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.condition)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.timePeriod)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DatePosted)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ListingId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ListingId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ListingId })
                </td>
            </tr>
        }
    </tbody>
</table>

WOA.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WOA.WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WOA.WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web of Antiquities</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Listing" asp-action="Index">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WOA.WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>